version: "3"

services:
  web:
    image: ded-moroz:client-latest
    container_name: client
    restart: always
    ports:
      - "1010:5180"

  server:
    image: ded-moroz:server-latest
    container_name: server
    environment:
      OPENAI_API_KEY: ""
      PORT: "5000"
    restart: always
    ports:
      - "5000:5000"
